Team-Qampus/Quampus_BE

Jenkinsfile, build.gradle, docker-compose.yml
=> [#46]jenkins 파일 및 Docker-compose 파일 수정

build.gradle
=> [#46]java-21설정

build.gradle
=> [#46]java-17설정

docker-compose.yml
=> [#46]Docker-compose설정

Dockerfile, docker-compose.yml
=> [#52]fix cross origin swagger

Jenkinsfile, docker-compose.yml
=> [#52]Jenkins 파일 수정

docker-compose.yml
=> [#52]docker-compose 파일 수정

build.gradle, src/main/java/swyp/qampus/login/config/ModuleConfig.java, src/main/java/swyp/qampus/login/config/WebOAuthSecurityConfig.java, src/main/java/swyp/qampus/login/controller/OAuthController.java, src/main/java/swyp/qampus/login/converter/OAuthConverter.java, src/main/java/swyp/qampus/login/converter/UserConverter.java, src/main/java/swyp/qampus/login/entity/User.java, src/main/java/swyp/qampus/login/service/CompleteSignupService.java, src/main/resources/application-secret.properties, src/main/resources/application.properties
> #60 카카오 로그인 오류 수정
- jackson 의존성 추가
- Module Config 추가
- Security 수정
- OAuthController 수정
- UserConverter 수정(순서)
- User 객체 빌더에 University 추가
- 완전 저장 메서드 수정
>
=> #60 카카오 로그인 오류 수정

src/main/java/swyp/qampus/curious/repository/CuriousCustomRepositoryImpl.java, src/main/resources/application.properties
=> [#63]package 재성정

src/main/resources/application.properties
> #67 카카오 로그인 설정 수정
> - properties 설정 변경
>
=> 카카오 로그인 설정 수정

Jenkinsfile, docker-compose.yml
=> [#68]Jenkins,docker-compose.yml 수정

src/main/java/swyp/qampus/login/controller/OAuthController.java, src/main/java/swyp/qampus/login/dto/TokenResponseDto.java, src/main/java/swyp/qampus/login/util/JWTUtil.java
#73
> 테스트용 프리패스 토큰 발급하는 기능 구현
>
=> [#73]프리패스 토큰 발급 기능 구현

src/main/java/swyp/qampus/university/controller/UniversityController.java, src/main/java/swyp/qampus/university/service/UniversityService.java, src/main/java/swyp/qampus/university/service/UniversityServiceImpl.java
=> [#84]랭킹 토큰 파라미터 제거

src/main/java/swyp/qampus/login/util/JWTUtil.java
=> [#86]테스트 유저 생성

docker-compose.yml, my.cnf
=> [#90]my.cnf 추가

src/main/java/swyp/qampus/answer/domain/ChoiceRequestDto.java, src/main/java/swyp/qampus/university/domain/response/UniversityDetailResponseDto.java
=> [#92]ChoiceRequestDto @NoArgsConstructor 추가

src/main/java/swyp/qampus/category/domain/CategoryType.java
=> [#79]카테고리 타입 추가

src/main/java/swyp/qampus/answer/controller/AnswerController.java
#94
> /answers/search 요청 시에 요청 파라미터 매개변수 지정
>
=> [#94]질문 검색하기 요청 파라미터 수정

src/main/java/swyp/qampus/answer/service/AnswerServiceImpl.java, src/main/java/swyp/qampus/curious/repository/CuriousRepository.java, src/main/java/swyp/qampus/question/domain/QuestionDetailResponseDto.java, src/main/resources/application.properties
#88
> response 시 나도 궁금해요 선택 유무 추가
>
=> [#88]질문 상세보기 수정

build.gradle, src/main/generated/swyp/qampus/login/entity/QUser.java, src/main/generated/swyp/qampus/university/domain/QUniversity.java, src/main/java/swyp/qampus/answer/service/AnswerServiceImpl.java, src/main/java/swyp/qampus/home/dto/UserHomeDto.java, src/main/java/swyp/qampus/home/service/HomeServiceImpl.java, src/main/java/swyp/qampus/login/entity/User.java, src/main/java/swyp/qampus/login/repository/UserRepository.java, src/main/java/swyp/qampus/login/repository/UserRepositoryCustom.java, src/main/java/swyp/qampus/login/repository/UserRepositoryCustomImpl.java, src/main/java/swyp/qampus/login/service/UserService.java, src/main/java/swyp/qampus/login/service/impl/UserServiceImpl.java, src/main/java/swyp/qampus/login/util/JWTFilter.java, src/main/java/swyp/qampus/university/domain/University.java, src/main/java/swyp/qampus/university/repository/UniversityRepositoryCustom.java, src/main/java/swyp/qampus/university/repository/UniversityRepositoryCustomImpl.java, src/main/java/swyp/qampus/university/service/UniversityService.java, src/main/java/swyp/qampus/university/service/UniversityServiceImpl.java, src/main/resources/application-test.properties, src/test/java/swyp/qampus/university/repository/UniversityRepositoryCustomImplTest.java
=> [#72]홈화면 학과별/학교별 월간 랭킹 비교 조회 구현

src/main/java/swyp/qampus/question/controller/QuestionController.java, src/main/java/swyp/qampus/question/domain/CreateQuestionResponseDto.java, src/main/java/swyp/qampus/question/service/QuestionService.java, src/main/java/swyp/qampus/question/service/QuestionServiceImpl.java
#97 
> 질문 생성 시 question_id 응답
>
=> [#97]질문 생성 시 question_id 응답

src/main/java/swyp/qampus/answer/controller/AnswerController.java, src/main/java/swyp/qampus/login/controller/UserController.java, src/main/java/swyp/qampus/login/service/UserService.java, src/main/java/swyp/qampus/login/service/impl/UserServiceImpl.java
#96 
- `UserServiceImple`에서 testUser 생성 메서드 누락 수정
>
=> [Hotfix]Revert 95 94 fix search questions

src/main/java/swyp/qampus/test/HealthCheckController.java
=> [#106]healthCheck Controller 추가

src/main/java/swyp/qampus/ai/config/OpenAiConfig.java, src/main/java/swyp/qampus/login/config/RestTemplateConfig.java
=> [#106]RestTemplate timeout 설정

src/main/generated/swyp/qampus/login/entity/QUser.java, src/main/java/swyp/qampus/answer/service/AnswerServiceImpl.java, src/main/java/swyp/qampus/login/config/WebOAuthSecurityConfig.java, src/main/java/swyp/qampus/login/service/impl/UserServiceImpl.java, src/main/java/swyp/qampus/question/domain/QuestionDetailResponseDto.java, src/main/resources/application.properties
#110 
- 카카오 로그인 JWT Filter 수정
>
=> [#110] build crash

src/main/java/swyp/qampus/login/util/JWTUtil.java
=> [#116]jwtfilter 로직 수정

src/main/java/swyp/qampus/login/util/JWTUtil.java
=> fix:Jwt 로직 변경

src/main/java/swyp/qampus/answer/controller/AnswerController.java
#120 
> 질문 검색 시 쿼리 파라미터 이름 지정
>
=> [#120]질문 검색하기 기능 오류 해결

src/main/java/swyp/qampus/ai/service/AiServiceImpl.java, src/main/java/swyp/qampus/ai/verification/CheckQuestionVerificationService.java, src/main/java/swyp/qampus/ai/verification/CheckQuestionVerificationServiceImpl.java, src/main/resources/application.properties
#123 
- 같은 문자 반복 검증
- 자음/모음만 반복 검증
- 의미 있는 단어 포함 여부 검증
- 입력 길이 검증(5자 이상)
>
=> [#123]verification system of gpt

src/main/generated/swyp/qampus/activity/QActivity.java, src/main/generated/swyp/qampus/activity/dto/QRecentActivityResponseDto.java, src/main/generated/swyp/qampus/university/domain/QUniversity.java, src/main/java/swyp/qampus/activity/Activity.java, src/main/java/swyp/qampus/activity/ActivityType.java, src/main/java/swyp/qampus/activity/controller/ActivityController.java, src/main/java/swyp/qampus/activity/dto/RecentActivityResponseDto.java, src/main/java/swyp/qampus/activity/repository/ActivityCustomRepository.java, src/main/java/swyp/qampus/activity/repository/ActivityCustomRepositoryImpl.java, src/main/java/swyp/qampus/activity/repository/ActivityRepository.java, src/main/java/swyp/qampus/activity/service/ActivityService.java, src/main/java/swyp/qampus/activity/service/ActivityServiceImpl.java, src/main/java/swyp/qampus/answer/service/AnswerServiceImpl.java, src/main/java/swyp/qampus/login/config/data/RedisCustomService.java, src/main/java/swyp/qampus/login/config/data/RedisCustomServiceImpl.java, src/main/java/swyp/qampus/login/service/impl/UserServiceImpl.java, src/main/java/swyp/qampus/question/service/QuestionServiceImpl.java, src/main/java/swyp/qampus/university/domain/University.java, src/main/java/swyp/qampus/university/repository/UniversityRepository.java, src/main/resources/application.properties
=> [#125]대학교별 최신 활동 내역 5개 조회

src/main/java/swyp/qampus/activity/controller/ActivityController.java, src/main/java/swyp/qampus/activity/dto/RecentActivityResponseDto.java
=> [#125]ActivityController Swagger 업데이트

src/main/java/swyp/qampus/university/controller/UniversityController.java, src/main/java/swyp/qampus/university/repository/UniversityRepositoryCustomImpl.java, src/main/java/swyp/qampus/university/service/UniversityService.java, src/main/java/swyp/qampus/university/service/UniversityServiceImpl.java
#125 
- `Group By` 적용하지 않아 여러 개의 결과 반환 시 Sql오류 발생 해결
>
=> [#125]UniversityDetail 500 오류 fix

src/main/java/swyp/qampus/openApi/GetLocationUtil.java, src/main/java/swyp/qampus/openApi/LocationDto.java, src/main/java/swyp/qampus/university/repository/UniversityRepositoryCustomImpl.java
=> 129 feat university location

src/main/generated/swyp/qampus/university/domain/response/QUniversityDetailResponseDto.java, src/main/java/swyp/qampus/university/domain/response/UniversityDetailResponseDto.java, src/main/java/swyp/qampus/university/repository/UniversityRepositoryCustomImpl.java
=> refact:UniversityDetal rank 추가

src/main/java/swyp/qampus/activity/controller/ActivityController.java, src/main/java/swyp/qampus/activity/service/ActivityService.java, src/main/java/swyp/qampus/activity/service/ActivityServiceImpl.java, src/main/java/swyp/qampus/university/domain/response/UniversityRankResponseDto.java
=> [#129]activity/detail 토큰 제거

src/main/java/swyp/qampus/answer/controller/AnswerController.java, src/main/java/swyp/qampus/answer/service/AnswerService.java, src/main/java/swyp/qampus/answer/service/AnswerServiceImpl.java
#134 
- 더미데이터 삽입 자동화를 위해 답변 생성 시 answerId반환
>
=> [#134]Answer create시 answerId반환

src/main/java/swyp/qampus/activity/service/ActivityServiceImpl.java
- search 조회 시 대학교가 존재하지 않을 시 빈배열 반환
>
=> [#134]대학교 존재하지 않을 시 빈 배열 반환

src/main/java/swyp/qampus/university/domain/response/UniversityRankResponseDto.java
=> [#140]longitude,latitude 순서 변경

src/main/java/swyp/qampus/answer/service/AnswerServiceImpl.java, src/main/java/swyp/qampus/question/service/QuestionServiceImpl.java
=> [#140]이미지 업로드 조건 추가

src/main/java/swyp/qampus/ai/service/AiServiceImpl.java, src/main/java/swyp/qampus/ai/verification/CheckQuestionVerificationServiceImpl.java, src/main/java/swyp/qampus/university/controller/UniversityController.java, src/main/java/swyp/qampus/university/domain/University.java, src/main/java/swyp/qampus/university/service/UniversityService.java, src/main/java/swyp/qampus/university/service/UniversityServiceImpl.java
=> [#140]학교 이름 수정

src/main/java/swyp/qampus/image/service/ImageServiceImpl.java, src/main/java/swyp/qampus/login/service/CompleteSignupService.java, src/main/java/swyp/qampus/test/TestController.java
#145 
- 대학교명 입력 시 '학교'가 들어가 있으면 삭제 처리
>
=> [#145]university detail enhancement

src/main/java/swyp/qampus/login/service/impl/UserServiceImpl.java, src/main/java/swyp/qampus/openApi/GetLocationUtil.java, src/main/java/swyp/qampus/university/domain/University.java
=> refact:test user생성 시 대학교 존재여부 수정

src/main/java/swyp/qampus/answer/controller/AnswerController.java, src/main/java/swyp/qampus/answer/domain/CreateAnswerResponseDto.java, src/main/resources/application.properties
=> refat:답변 생성 시 반환 Dto 변경

src/main/java/swyp/qampus/answer/domain/CreateAnswerResponseDto.java
=> fix:답변 생성 시 반환 dto  수정

src/main/java/swyp/qampus/activity/Activity.java, src/main/java/swyp/qampus/ai/domain/Ai.java, src/main/java/swyp/qampus/answer/domain/Answer.java, src/main/java/swyp/qampus/curious/domain/Curious.java, src/main/java/swyp/qampus/like/domain/Like.java, src/main/java/swyp/qampus/login/entity/User.java, src/main/java/swyp/qampus/question/domain/Question.java, src/main/java/swyp/qampus/university/domain/University.java
=> refact:PK 증가 방식 변경
